### PR TITLE
Updated the vmd file output

### PR DESCRIPTION
**Pull request by kratman**
I updated the routine which writes the .vmd files. This mostly updates the VMD scripts to be compatible with v 1.9.x.

Changes:
- [x] Removed unneeded white space
- [x] Changed comments to show that the file was created by NCIPLOT not VMD
- [x] Added instructions on how to run the script in VMD
- [x] Fixed the viewplist and fixedlist commands which need to be followed by {} in VMD 1.9.x
- [x] Reduced the size of the CPK spheres so that pictures crystals and proteins are clearer
- [x] Removed the "set colorcmds" setting which does not seem to do anything
- [x] Turned off depth cuing which is turned on by default in VMD

### CODE REVIEW

**Comment by aoterodelaroza** [comment]
Looks good. Any particular reason to scale down the atoms, though?

**Comment by kratman** [comment]
I changed the sphere scale because I felt that some features of the surfaces (e.g. the small hydrogen bond disks) were obscured when there was a large number of atoms. I had to reduce the size of the CPK spheres every time I opened an NCI plot, so I (perhaps incorrectly) assumed that others had difficulty seeing it too.

Visualization settings are largely personal preference, so I will gladly change it back if you think I made the spheres too small.

**Comment by aoterodelaroza** [comment]
I've never heard from any user about this problem before, so I'm inclined to say revert to the defaults. However, if you e-mail me the problematic nci and the wfn/wfx/xyz, I'll take a look.

**Comment by kratman** [comment]
Ok I changed it back to 1.0 and uploaded the commit.

**Comment by aoterodelaroza** [comment]
Thanks, merged.

**Pull request merged**
